=== ericksanzjme/website/xsd/portada.xsd
<xs:schema version="1.0"
           xmlns:xs="http://www.w3.org/2001/XMLSchema"
           elementFormDefault="qualified">
    <xs:element name="contenedor">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="portada" minOccurs="1" maxOccurs="1">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="imagen"  minOccurs="1" maxOccurs="1">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:pattern value="../[a-zA-Z]*/[a-zA-z]*/imagen[0-9]{1}.png"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="altportada" minOccurs="1" maxOccurs="1">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:pattern value="[a-zA-Z]*"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="titulo" minOccurs="1" maxOccurs="1">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:pattern value="Coche[a-zA-Z]{1}[0-9]{2}PVT"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="enlaces" maxOccurs="1">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="inicio" minOccurs="1" maxOccurs="1">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:enumeration value="Inicio"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="Coches" minOccurs="1" maxOccurs="1">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:enumeration value="Productos"/>
                                        <xs:enumeration value="Coches"/>
                                        <xs:enumeration value="Autos"/>
                                        <xs:enumeration value="Vehiculos"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="Soporte" minOccurs="1" maxOccurs="1">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:enumeration value="Soporte"/>
                                        <xs:enumeration value="Servicio"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="Mas" minOccurs="1" maxOccurs="1">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:length value="3"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="central" minOccurs="1" maxOccurs="2">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="titulo"  type="xs:string"/>
                            <xs:element name="imagen" minOccurs="1" maxOccurs="1" >
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:pattern value="../[a-zA-Z]*/[a-zA-z]*/imagen[0-9]{1}.png"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="altcentral">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:pattern value="[a-zA-Z]*"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="texto" type="xs:string" minOccurs="1" maxOccurs="1" />
                            <xs:element name="precio">
                                <xs:simpleType>
                                    <xs:restriction base="xs:decimal">
                                        <xs:totalDigits value="11"/>
                                        <xs:fractionDigits value="6"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="final" minOccurs="1" maxOccurs="1">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="masinfo"  minOccurs="1" maxOccurs="1">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="titulo" type="xs:string" maxOccurs="1"/>
                                        <xs:element name="imagen" minOccurs="1" maxOccurs="1">
                                            <xs:simpleType>
                                                <xs:restriction base="xs:string">
                                                    <xs:pattern value="../[a-zA-Z]*/[a-zA-z]*/imagen[0-9]{1}.png"/>
                                                </xs:restriction>
                                            </xs:simpleType>
                                        </xs:element>
                                        <xs:element name="altfinal" maxOccurs="1">
                                            <xs:simpleType>
                                                <xs:restriction base="xs:string">
                                                    <xs:pattern value="[a-zA-Z]*"/>
                                                </xs:restriction>
                                            </xs:simpleType>
                                        </xs:element>
                                        <xs:element name="texto" type="xs:string" maxOccurs="1"/>
                                        <xs:element name="contexto" type="xs:string" maxOccurs="1"/>
                                        <xs:element name="enlace" maxOccurs="1">
                                            <xs:simpleType>
                                                <xs:restriction base="xs:string">
                                                    <xs:enumeration value="Mas productos"/>
                                                </xs:restriction>
                                            </xs:simpleType>
                                        </xs:element>
                                        <xs:element name="telefono" maxOccurs="1">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="contexto" maxOccurs="1">
                                                        <xs:simpleType>
                                                            <xs:restriction base="xs:string">
                                                                <xs:enumeration value="Informacion de contacto"/>
                                                                <xs:enumeration value="Donde contactarnos"/>
                                                                <xs:enumeration value="Contactanos"/>
                                                            </xs:restriction>
                                                        </xs:simpleType>
                                                    </xs:element>
                                                    <xs:element name="numero" maxOccurs="1">
                                                        <xs:simpleType>
                                                            <xs:restriction base="xs:string">
                                                                <xs:length value="9"/>
                                                            </xs:restriction>
                                                        </xs:simpleType>
                                                    </xs:element>
                                                    <xs:element name="gmail" maxOccurs="2">
                                                        <xs:simpleType>
                                                            <xs:restriction base="xs:string">
                                                                <xs:pattern value="[a-zA-Z]{1,15}@[a-z]{1,25}[.][a-z]{2,4}"/>
                                                            </xs:restriction>
                                                        </xs:simpleType>
                                                    </xs:element>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== ericksanzjme/website/xml/portada.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="portada.xsl"?>
<contenedor 
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
    xsi:noNamespaceSchemaLocation="../xsd/portada.xsd">
    <portada>
        <imagen>../imagenes/portada/imagen1.png</imagen>
        <altportada>portada</altportada>
        <titulo>CocheS20PVT</titulo>
    </portada>
    <enlaces>
        <inicio>Inicio</inicio>
        <Coches>Autos</Coches>
        <Soporte>Soporte</Soporte>
        <Mas>Mas</Mas>
    </enlaces>
    <central>
        <titulo>Series especiales ilimitadas</titulo>
        <imagen>../imagenes/central/imagen1.png</imagen>
        <altcentral>central</altcentral>
        <texto>Los nuevos Ferrari Monza SP1 y SP2 nacen de un nuevo concepto,
            denominado ‘Icona’, que conecta con el pasado a través del hilo conductor de los vehículos más evocadores de la propia historia. 
            Crea un nuevo segmento de series especiales limitadas desarrollado para clientes y coleccionistas Ferrari.</texto>
        <precio>35.000000</precio>
    </central>
    <final>
        <masinfo>
            <titulo>Descubre el ferrari Portofino</titulo>
            <imagen>../imagenes/fin/imagen1.png</imagen>
            <altfinal>final</altfinal>
            <texto>solicitar mas informacion </texto>
            <contexto>¡Consigue el coche de tus sueños, el mercado de automóviles online más grande de Europa! </contexto>
            <enlace>Mas productos</enlace>
            <telefono>
                <contexto>Donde contactarnos</contexto>
                <numero>657070592</numero>
                <gmail>Coches@gmail.com</gmail>
            </telefono>
        </masinfo>
    </final>
</contenedor>
